name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      LARK_APP_ID: ${{ secrets.LARK_APP_ID }}
      LARK_APP_SECRET: ${{ secrets.LARK_APP_SECRET }}
      LARK_WEBHOOK_URL: ${{ secrets.LARK_WEBHOOK_URL }}
      LARK_BOT_SECRET: ${{ secrets.LARK_BOT_SECRET }}
      LARK_GITHUB_EMAIL_MAP: ${{ secrets.LARK_GITHUB_EMAIL_MAP }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Generate env.yaml
        run: |
          echo "github:" > env.yaml
          echo "  app_id: ${APP_ID}" >> env.yaml
          echo "  private_key: |-" >> env.yaml
          printf "%b\n" "${APP_PRIVATE_KEY}" | sed 's/^/    /' >> env.yaml
          echo "" >> env.yaml

          echo "lark:" >> env.yaml
          echo "  app_id: ${LARK_APP_ID}" >> env.yaml
          echo "  app_secret: ${LARK_APP_SECRET}" >> env.yaml
          echo "  github_to_email_map: ${LARK_GITHUB_EMAIL_MAP}" >> env.yaml
          echo "  secret: ${LARK_BOT_SECRET}" >> env.yaml
          echo "  webhook_url: ${LARK_WEBHOOK_URL}" >> env.yaml

      - name: Run auto assign
        run: go run ./cmd/main.go